bijarnia_mahay_2022 <- readr::read_csv('data-raw/bijarnia_mahay_2022.csv', col_types = cols(
  study = col_character(),
  id = col_character(),
  family = col_character(),
  individual = col_factor(levels = c("1", "2", "3", "4"), ordered = FALSE, include_na = FALSE),
  deceased = col_logical(),
  survival_time = col_double(),
  variant_type = col_factor(levels = c("compound heterozygote", "homozygote"), ordered = FALSE, include_na = FALSE),
  locus_1 = col_double(),
  locus_2 = col_double(),
  gender = col_factor(levels = c("female", "male"), ordered = FALSE, include_na = FALSE),
  ethnicity = col_character(),
  consanguineous = col_logical(),
  termination = col_logical(),
  birth_gestation = col_double(),
  route_vaginal_vs_c_sect = col_factor(levels = c("CS", "SVD"), ordered = FALSE, include_na = FALSE),
  birth_weight = col_double(),
  birth_ofc = col_double(),
  birth_length = col_double(),
  age_at_demise = col_double(),
  age_at_last_follow_up = col_double(),
  microcephaly_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  sgp_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  iugr_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  talipes_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  rocker_bottom_feet_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  contractures_hands_deform_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  vocal_cord_palsy_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  arthrogryposis_contractures_other_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  hypercapnia_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  cleft_lip_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  inspiratory_stridor_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  polyhydramnios_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  coarse_facial_features_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  oligohydramnios_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  respiratory_distress_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  tracheostomy_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  prominent_ears_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  posteriorly_angulated_ears_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  prominent_philtrum_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  upper_lip_dysmorph_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  hypomyelination_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  cerebellar_hypoplasia_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  short_palpebral_fissures_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  epicanthal_folds_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  tube_feed_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  dysmorphic_features_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  patent_ductus_arteriosus_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  small_anterior_fontanel_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  receding_forehead_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  tracheo_laryngomalacia_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  gerd_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  thin_corpus_collosum_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  feeding_swallow_dysfxn_ind = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  seizures_age_started = col_factor(levels = c("7 weeks", "around 2ys", "from birth", "from birth (1st week)", 
                                               "no clinical seizure", "no clinical sizure", "none", "None", 
                                               "yes", "yes (< 4 months)", "yes (4 months)", "yes (unknown)"), ordered = FALSE, include_na = FALSE),
  seizure_type_s = col_character(),
  eeg = col_character(),
  sleeping_problem = col_character(),
  behavioral_issues = col_character(),
  skeletal_changes_scoliosis = col_character(),
  hip_luxation = col_character(),
  development_head_control = col_character(),
  sitting_unsupported = col_character(),
  crawling = col_character(),
  walking = col_character(),
  speech = col_character(),
  iq_int_disability = col_character(),
  cp = col_character(),
  performance = col_character(),
  neuro_exam_eye_mvts_nystagmus = col_character(),
  strabismus = col_character(),
  feeding_swallow_dysfxn = col_character(),
  gag = col_character(),
  tone = col_character(),
  strength = col_character(),
  sensory_deficits = col_character(),
  abnormal_mvts = col_character(),
  dtr = col_character(),
  other_neuro_signs = col_character(),
  sensory_vision = col_character(),
  hearing = col_character(),
  other_organs = col_character(),
  endocrinology = col_character(),
  functional_tests = col_character(),
  metabolic_investigation = col_character(),
  cardiology = col_character(),
  seizure = col_character(),
  agenesis_of_corpus_callosum = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  abnormal_pattern_of_cerebral_sulci = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  left_sided_gallbladder = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  suspected_brain_stem_dysfunction = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  spastic_tetraparesis = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  severe_developmental_delay = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  acidosis = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  small_thorax = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  cyanosis = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  intubation = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  apnea = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  mr_is_reportedly_with_migrational_defect = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  at_birth_sga = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  epilepsy_and_apnea = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  choanal_atresia_surgeries_for_transposition_of_the_great_arteries = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  interventricular_and_interatrial_defects = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  smooth_philtrum = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  thin_lips = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  bilateral_simian_creases = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  low_anterior_hairline = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  short_philtrum = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  prominent_nose_bridge = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  depressed_nasal_bridge = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  prominent_suture_ridges = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  hypotelorism = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  hypertrichosis_of_lower_back = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  decreased_craniofacial_ratio = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  there_is_overlapping_of_the_sutures = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  bitemporal_narrowing = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  short_upturned_nose = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  short_neck = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  upward_sweep_of_hair = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  arched_eye_brows = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  bulbous_nose = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  prominent_lower_lip = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  broad_chin = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  prognathism = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  asd = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  left_multicystic_dysplastic_kidney = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  anteriorly_placed_anus = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  dilated_cardiomyopathy = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  cryptorchidism = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  hirsutism = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  intestinal_malrotation = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  dysphagia = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  intermittent_sinus_bradycardia = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  bilateral_staphylomas = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  lissencephaly = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  echogenic_choroid_plexus_on_head_us = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  head_us_mild_ventriculomegaly = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  brain_parenchyma_appears_homogeneous_without_evidence_of_focal_lesion = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  hypoplastic_cerebellum = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  borderline_small_brainstem = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  abnormal_cerebellar_folia = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  mild_vermian_hypoplasia = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  asymmetry_of_lateral_ventricles = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  lissencephaly_and_cerebellar_hypoplasia = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  signs_of_hypoxic_encephalopathy = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  mild_dilation_of_virchow_robins_spaces = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  pectus_excavatum = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  widely_spaced_nipples = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  respiratory_infections = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  enlarged_ventricles = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  eeg_normal = col_logical(),
  bifid_uvula = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE),
  under_developed_cerebellar_inferior_vermis = col_factor(levels = c("0", "1"), ordered = FALSE, include_na = FALSE)
))


usethis::use_data(bijarnia_mahay_2022, overwrite = TRUE)
